name: Fles Analysis Deploy           # Workflow 이름

on:                                  # Event 감지
  push:
    tags:
     - '*'                           # 태그 추가시 task 수행
     
jobs:                                # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@master
      
      - name: Check Node v            # Node v 확인
        run: node -v

      - name: Install Dependencies    # 의존 파일 설치
        run: yarn install 

      - name: Build                   # React Build
        run: yarn build

      - name: Version Named
        run: cd dist && mkdir $(git describe --tags --abbrev=0) && mv bundle.js $(git describe --tags --abbrev=0)/bundle.js
      
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read 
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }} #/$(git describe --tags --abbrev=0)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DEST_DIR: $(git describe --tags --abbrev=0)
          SOURCE_DIR: "dist"
          
